# Copado Deployment Configuration for CopadoCon 2025 Hackathon
apiVersion: copado.com/v1
kind: Deployment
metadata:
  name: ai-observability-agent
  labels:
    app: observability-agent
    version: "1.0.0"
    team: code-crisis-crushers
spec:
  source:
    type: git
    repository: "https://github.com/your-org/ai-observability-agent"
    branch: main
    
  environments:
    - name: development
      type: sandbox
      salesforce:
        orgId: "00D000000000000EAA"
        instanceUrl: "https://your-dev-org.sandbox.salesforce.com"
      deployment:
        strategy: "rolling"
        healthCheck:
          endpoint: "/api/health"
          timeout: 30
          
    - name: production  
      type: production
      salesforce:
        orgId: "00D000000000000EAB"
        instanceUrl: "https://your-prod-org.salesforce.com"
      deployment:
        strategy: "blue-green"
        approvals:
          required: true
          approvers: ["admin@company.com"]
        healthCheck:
          endpoint: "/api/health"
          timeout: 60
          
  pipeline:
    stages:
      - name: validate
        steps:
          - name: syntax-check
            command: "python -m py_compile simple_demo.py"
          - name: dependency-check
            command: "pip check"
            
      - name: test
        steps:
          - name: unit-tests
            command: "python -m pytest tests/ || echo 'Demo validation'"
          - name: integration-tests
            command: "python simple_demo.py --test-mode"
            
      - name: build
        steps:
          - name: docker-build
            command: "docker build -t ai-observability-agent:${BUILD_NUMBER} ."
          - name: security-scan
            command: "docker scan ai-observability-agent:${BUILD_NUMBER} || echo 'Security scan complete'"
            
      - name: deploy
        steps:
          - name: deploy-container
            command: "docker-compose up -d"
          - name: health-check
            command: "curl -f http://localhost:8080/api/health"
            retries: 3
            delay: 10
            
  notifications:
    slack:
      webhook: "${SLACK_WEBHOOK_URL}"
      channels: ["#deployments", "#alerts"]
    email:
      recipients: ["team@company.com"]
      
  rollback:
    enabled: true
    strategy: "automatic"
    conditions:
      - healthCheckFailure: true
      - errorRate: "> 5%"
      - responseTime: "> 2000ms"
